/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package new_bank;
import javax.swing.JOptionPane;
/**
 *
 * @author farhan
 */
public class MenuTeller extends javax.swing.JFrame {

    /**
     * Creates new form MenuTeller
     */
    Teller menuteller = new Teller();
    MainMenu mainmenu = new MainMenu();
    public MenuTeller() {
        initComponents();
        PanelLoginTeller.setVisible(true);
        MenuTeller1.setVisible(false);
        PanelCekSaldoTeller.setVisible(false);
        PanelSimpanTeller.setVisible(false);
        PanelTransferTeller.setVisible(false);
        PanelAmbilTeller.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLoginTeller = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Usernameteller = new javax.swing.JTextField();
        jBLoginTeller = new javax.swing.JButton();
        jBKembaliLogin = new javax.swing.JButton();
        Passwordteller = new javax.swing.JPasswordField();
        MenuTeller1 = new javax.swing.JPanel();
        jLNasabah = new javax.swing.JLabel();
        jBMenuCekSaldoTeller = new javax.swing.JButton();
        jBMenuSimpanTeller = new javax.swing.JButton();
        jBMenuAmbilTeller = new javax.swing.JButton();
        jBTransferTeller = new javax.swing.JButton();
        jBLogoutTeller = new javax.swing.JButton();
        jLabelTeller = new javax.swing.JLabel();
        PanelCekSaldoTeller = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLSaldo2 = new javax.swing.JLabel();
        jBKembaliCekSaldo2 = new javax.swing.JButton();
        PanelSimpanTeller = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTSimpan = new javax.swing.JTextField();
        jBSimpan = new javax.swing.JButton();
        jBKembaliSimpan = new javax.swing.JButton();
        PanelTransferTeller = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTRekTujuan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTNominalTransfer = new javax.swing.JTextField();
        jBTombolTransfer = new javax.swing.JButton();
        jBKembaliSimpan1 = new javax.swing.JButton();
        PanelAmbilTeller = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTAmbil = new javax.swing.JTextField();
        jBKembaliAmbil = new javax.swing.JButton();
        jBAmbil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelLoginTeller.setBackground(new java.awt.Color(26, 15, 128));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(251, 241, 241));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN TELLER");

        jLabel2.setForeground(new java.awt.Color(254, 247, 247));
        jLabel2.setText("Username");

        jLabel3.setForeground(new java.awt.Color(253, 251, 251));
        jLabel3.setText("Password");

        Usernameteller.setText("Username");
        Usernameteller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernametellerActionPerformed(evt);
            }
        });

        jBLoginTeller.setBackground(new java.awt.Color(244, 227, 29));
        jBLoginTeller.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBLoginTeller.setForeground(new java.awt.Color(24, 19, 52));
        jBLoginTeller.setText("Login");
        jBLoginTeller.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBLoginTeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLoginTellerActionPerformed(evt);
            }
        });

        jBKembaliLogin.setBackground(new java.awt.Color(206, 30, 5));
        jBKembaliLogin.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBKembaliLogin.setForeground(new java.awt.Color(254, 254, 254));
        jBKembaliLogin.setText("Kembali");
        jBKembaliLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBKembaliLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBKembaliLoginActionPerformed(evt);
            }
        });

        Passwordteller.setText("jPasswordField1");

        javax.swing.GroupLayout PanelLoginTellerLayout = new javax.swing.GroupLayout(PanelLoginTeller);
        PanelLoginTeller.setLayout(PanelLoginTellerLayout);
        PanelLoginTellerLayout.setHorizontalGroup(
            PanelLoginTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginTellerLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(PanelLoginTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLoginTellerLayout.createSequentialGroup()
                        .addComponent(jBKembaliLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBLoginTeller, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelLoginTellerLayout.createSequentialGroup()
                        .addGroup(PanelLoginTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelLoginTellerLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Passwordteller))
                            .addGroup(PanelLoginTellerLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(Usernameteller, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLoginTellerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        PanelLoginTellerLayout.setVerticalGroup(
            PanelLoginTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginTellerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLoginTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Usernameteller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLoginTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Passwordteller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(PanelLoginTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLoginTeller)
                    .addComponent(jBKembaliLogin))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        MenuTeller1.setBackground(new java.awt.Color(26, 15, 128));

        jLNasabah.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLNasabah.setForeground(new java.awt.Color(251, 241, 241));
        jLNasabah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLNasabah.setText("WELCOME USER");

        jBMenuCekSaldoTeller.setBackground(new java.awt.Color(244, 227, 29));
        jBMenuCekSaldoTeller.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBMenuCekSaldoTeller.setForeground(new java.awt.Color(24, 19, 52));
        jBMenuCekSaldoTeller.setText("Cek Saldo");
        jBMenuCekSaldoTeller.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBMenuCekSaldoTeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMenuCekSaldoTellerActionPerformed(evt);
            }
        });

        jBMenuSimpanTeller.setBackground(new java.awt.Color(244, 227, 29));
        jBMenuSimpanTeller.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBMenuSimpanTeller.setForeground(new java.awt.Color(24, 19, 52));
        jBMenuSimpanTeller.setText("Simpan");
        jBMenuSimpanTeller.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBMenuSimpanTeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMenuSimpanTellerActionPerformed(evt);
            }
        });

        jBMenuAmbilTeller.setBackground(new java.awt.Color(244, 227, 29));
        jBMenuAmbilTeller.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBMenuAmbilTeller.setForeground(new java.awt.Color(24, 19, 52));
        jBMenuAmbilTeller.setText("Ambil");
        jBMenuAmbilTeller.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBMenuAmbilTeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMenuAmbilTellerActionPerformed(evt);
            }
        });

        jBTransferTeller.setBackground(new java.awt.Color(244, 227, 29));
        jBTransferTeller.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBTransferTeller.setText("Transfer");
        jBTransferTeller.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBTransferTeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTransferTellerActionPerformed(evt);
            }
        });

        jBLogoutTeller.setBackground(new java.awt.Color(206, 30, 5));
        jBLogoutTeller.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBLogoutTeller.setForeground(new java.awt.Color(254, 254, 254));
        jBLogoutTeller.setText("Logout");
        jBLogoutTeller.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBLogoutTeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLogoutTellerActionPerformed(evt);
            }
        });

        jLabelTeller.setForeground(new java.awt.Color(254, 254, 254));
        jLabelTeller.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTeller.setText("jLabel4");

        javax.swing.GroupLayout MenuTeller1Layout = new javax.swing.GroupLayout(MenuTeller1);
        MenuTeller1.setLayout(MenuTeller1Layout);
        MenuTeller1Layout.setHorizontalGroup(
            MenuTeller1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuTeller1Layout.createSequentialGroup()
                .addGroup(MenuTeller1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuTeller1Layout.createSequentialGroup()
                        .addGroup(MenuTeller1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MenuTeller1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLNasabah, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(MenuTeller1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(MenuTeller1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBMenuSimpanTeller, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMenuCekSaldoTeller, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMenuAmbilTeller, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBTransferTeller, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBLogoutTeller, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelTeller, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        MenuTeller1Layout.setVerticalGroup(
            MenuTeller1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuTeller1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLNasabah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTeller)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jBMenuCekSaldoTeller)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBMenuSimpanTeller)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBMenuAmbilTeller)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBTransferTeller)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBLogoutTeller)
                .addContainerGap())
        );

        PanelCekSaldoTeller.setBackground(new java.awt.Color(26, 15, 128));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CEK SALDO");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(254, 254, 254));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Saldo Anda  :");

        jLSaldo2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLSaldo2.setForeground(new java.awt.Color(254, 254, 254));
        jLSaldo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLSaldo2.setText("100000");

        jBKembaliCekSaldo2.setBackground(new java.awt.Color(206, 30, 5));
        jBKembaliCekSaldo2.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jBKembaliCekSaldo2.setForeground(new java.awt.Color(254, 254, 254));
        jBKembaliCekSaldo2.setText("Kembali");
        jBKembaliCekSaldo2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBKembaliCekSaldo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBKembaliCekSaldo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCekSaldoTellerLayout = new javax.swing.GroupLayout(PanelCekSaldoTeller);
        PanelCekSaldoTeller.setLayout(PanelCekSaldoTellerLayout);
        PanelCekSaldoTellerLayout.setHorizontalGroup(
            PanelCekSaldoTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCekSaldoTellerLayout.createSequentialGroup()
                .addGroup(PanelCekSaldoTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCekSaldoTellerLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCekSaldoTellerLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCekSaldoTellerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLSaldo2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelCekSaldoTellerLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jBKembaliCekSaldo2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelCekSaldoTellerLayout.setVerticalGroup(
            PanelCekSaldoTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCekSaldoTellerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLSaldo2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBKembaliCekSaldo2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelSimpanTeller.setBackground(new java.awt.Color(26, 15, 128));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(254, 254, 254));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("SIMPAN");

        jTSimpan.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTSimpan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTSimpan.setText("100000");

        jBSimpan.setBackground(new java.awt.Color(244, 227, 29));
        jBSimpan.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBSimpan.setText("Simpan");
        jBSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSimpanActionPerformed(evt);
            }
        });

        jBKembaliSimpan.setBackground(new java.awt.Color(206, 30, 5));
        jBKembaliSimpan.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBKembaliSimpan.setForeground(new java.awt.Color(254, 254, 254));
        jBKembaliSimpan.setText("Kembali");
        jBKembaliSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBKembaliSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBKembaliSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSimpanTellerLayout = new javax.swing.GroupLayout(PanelSimpanTeller);
        PanelSimpanTeller.setLayout(PanelSimpanTellerLayout);
        PanelSimpanTellerLayout.setHorizontalGroup(
            PanelSimpanTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSimpanTellerLayout.createSequentialGroup()
                .addGroup(PanelSimpanTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSimpanTellerLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelSimpanTellerLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(PanelSimpanTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelSimpanTellerLayout.createSequentialGroup()
                                .addComponent(jBKembaliSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSimpanTellerLayout.setVerticalGroup(
            PanelSimpanTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSimpanTellerLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelSimpanTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSimpan)
                    .addComponent(jBKembaliSimpan))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        PanelTransferTeller.setBackground(new java.awt.Color(26, 15, 128));

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(254, 254, 254));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("TRANSFER");

        jTRekTujuan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTRekTujuan.setText("1001");
        jTRekTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTRekTujuanActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(254, 254, 254));
        jLabel13.setText("Rekening Tujuan  :");

        jLabel14.setForeground(new java.awt.Color(254, 254, 254));
        jLabel14.setText("Nominal  :");

        jTNominalTransfer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTNominalTransfer.setText("50000");
        jTNominalTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNominalTransferActionPerformed(evt);
            }
        });

        jBTombolTransfer.setBackground(new java.awt.Color(244, 227, 29));
        jBTombolTransfer.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBTombolTransfer.setText("Transfer");
        jBTombolTransfer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBTombolTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTombolTransferActionPerformed(evt);
            }
        });

        jBKembaliSimpan1.setBackground(new java.awt.Color(206, 30, 5));
        jBKembaliSimpan1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBKembaliSimpan1.setForeground(new java.awt.Color(254, 254, 254));
        jBKembaliSimpan1.setText("Kembali");
        jBKembaliSimpan1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBKembaliSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBKembaliSimpan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTransferTellerLayout = new javax.swing.GroupLayout(PanelTransferTeller);
        PanelTransferTeller.setLayout(PanelTransferTellerLayout);
        PanelTransferTellerLayout.setHorizontalGroup(
            PanelTransferTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTransferTellerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelTransferTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTNominalTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTRekTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116))
            .addGroup(PanelTransferTellerLayout.createSequentialGroup()
                .addGroup(PanelTransferTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTransferTellerLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(PanelTransferTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)))
                    .addGroup(PanelTransferTellerLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelTransferTellerLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jBKembaliSimpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBTombolTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        PanelTransferTellerLayout.setVerticalGroup(
            PanelTransferTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTransferTellerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTRekTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTNominalTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelTransferTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTombolTransfer)
                    .addComponent(jBKembaliSimpan1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelAmbilTeller.setBackground(new java.awt.Color(26, 15, 128));

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(254, 254, 254));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("AMBIL");

        jTAmbil.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTAmbil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTAmbil.setText("100000");

        jBKembaliAmbil.setBackground(new java.awt.Color(206, 30, 5));
        jBKembaliAmbil.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBKembaliAmbil.setForeground(new java.awt.Color(254, 254, 254));
        jBKembaliAmbil.setText("Kembali");
        jBKembaliAmbil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBKembaliAmbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBKembaliAmbilActionPerformed(evt);
            }
        });

        jBAmbil.setBackground(new java.awt.Color(244, 227, 29));
        jBAmbil.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBAmbil.setText("Ambil");
        jBAmbil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAmbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAmbilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAmbilTellerLayout = new javax.swing.GroupLayout(PanelAmbilTeller);
        PanelAmbilTeller.setLayout(PanelAmbilTellerLayout);
        PanelAmbilTellerLayout.setHorizontalGroup(
            PanelAmbilTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAmbilTellerLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jBKembaliAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAmbilTellerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelAmbilTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAmbilTellerLayout.createSequentialGroup()
                        .addComponent(jTAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAmbilTellerLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))))
        );
        PanelAmbilTellerLayout.setVerticalGroup(
            PanelAmbilTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAmbilTellerLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelAmbilTellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAmbil)
                    .addComponent(jBKembaliAmbil))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(PanelLoginTeller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MenuTeller1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanelCekSaldoTeller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelAmbilTeller, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelTransferTeller, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelSimpanTeller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelLoginTeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MenuTeller1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelCekSaldoTeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelSimpanTeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelTransferTeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelAmbilTeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernametellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernametellerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernametellerActionPerformed

    private void jBLoginTellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoginTellerActionPerformed
        // TODO add your handling code here:
        String user = Usernameteller.getText();
        int pass = Integer.parseInt(Passwordteller.getText());

        if(menuteller.login(user,pass)){
            PanelLoginTeller.setVisible(false);
            MenuTeller1.setVisible(true);
            PanelCekSaldoTeller.setVisible(false);
            PanelSimpanTeller.setVisible(false);
            PanelTransferTeller.setVisible(false);
            PanelAmbilTeller.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null,"Account tidak ditemukan!!!");
        }
        jLNasabah.setText("WELCOME " + user);
        jLabelTeller.setText("Nama Teller : " + menuteller.namaTeller);
    }//GEN-LAST:event_jBLoginTellerActionPerformed

    private void jBKembaliLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBKembaliLoginActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        mainmenu.setVisible(true);
    }//GEN-LAST:event_jBKembaliLoginActionPerformed

    private void jBMenuCekSaldoTellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMenuCekSaldoTellerActionPerformed
        // TODO add your handling code here:
        MenuTeller1.setVisible(false);
        PanelCekSaldoTeller.setVisible(true);
        jLSaldo2.setText(menuteller.cekSaldo());
    }//GEN-LAST:event_jBMenuCekSaldoTellerActionPerformed

    private void jBMenuSimpanTellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMenuSimpanTellerActionPerformed
        // TODO add your handling code here:
        MenuTeller1.setVisible(false);
        PanelSimpanTeller.setVisible(true);

    }//GEN-LAST:event_jBMenuSimpanTellerActionPerformed

    private void jBMenuAmbilTellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMenuAmbilTellerActionPerformed
        // TODO add your handling code here:
        MenuTeller1.setVisible(false);
        PanelAmbilTeller.setVisible(true);

    }//GEN-LAST:event_jBMenuAmbilTellerActionPerformed

    private void jBTransferTellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTransferTellerActionPerformed
        // TODO add your handling code here:
        MenuTeller1.setVisible(false);
        PanelTransferTeller.setVisible(true);

    }//GEN-LAST:event_jBTransferTellerActionPerformed

    private void jBLogoutTellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLogoutTellerActionPerformed
        // TODO add your handling code here:
        MenuTeller1.setVisible(false);
        PanelLoginTeller.setVisible(true);
    }//GEN-LAST:event_jBLogoutTellerActionPerformed

    private void jBKembaliCekSaldo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBKembaliCekSaldo2ActionPerformed
        // TODO add your handling code here:
        MenuTeller1.setVisible(true);
        PanelCekSaldoTeller.setVisible(false);
    }//GEN-LAST:event_jBKembaliCekSaldo2ActionPerformed

    private void jBSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSimpanActionPerformed
        // TODO add your handling code here:
        long nominal = Long.parseLong(jTSimpan.getText());
        menuteller.simpan(nominal);
        JOptionPane.showMessageDialog(null,"Uang senilai "+nominal+" berhasil disimpan");
        MenuTeller1.setVisible(true);
        PanelSimpanTeller.setVisible(false);
    }//GEN-LAST:event_jBSimpanActionPerformed

    private void jBKembaliSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBKembaliSimpanActionPerformed
        // TODO add your handling code here:
        MenuTeller1.setVisible(true);
        PanelSimpanTeller.setVisible(false);
    }//GEN-LAST:event_jBKembaliSimpanActionPerformed

    private void jTRekTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTRekTujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTRekTujuanActionPerformed

    private void jTNominalTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNominalTransferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNominalTransferActionPerformed

    private void jBTombolTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTombolTransferActionPerformed
        // TODO add your handling code here:
        long rekening = Long.parseLong(jTRekTujuan.getText());
        long nominal = Long.parseLong(jTNominalTransfer.getText());

        if(menuteller.transfer(nominal, rekening)){
            JOptionPane.showMessageDialog(null,"Berhasil Ditransfer!!");
        }
        else{
            JOptionPane.showMessageDialog(null,"Rekening tidak Ditemukan/Saldo tidak cukup!!");
        }
        MenuTeller1.setVisible(true);
        PanelTransferTeller.setVisible(false);
    }//GEN-LAST:event_jBTombolTransferActionPerformed

    private void jBKembaliSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBKembaliSimpan1ActionPerformed
        // TODO add your handling code here:
        MenuTeller1.setVisible(true);
        PanelTransferTeller.setVisible(false);
    }//GEN-LAST:event_jBKembaliSimpan1ActionPerformed

    private void jBKembaliAmbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBKembaliAmbilActionPerformed
        // TODO add your handling code here:
        MenuTeller1.setVisible(true);
        PanelAmbilTeller.setVisible(false);
    }//GEN-LAST:event_jBKembaliAmbilActionPerformed

    private void jBAmbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAmbilActionPerformed
        // TODO add your handling code here:
        long nominal = Long.parseLong(jTAmbil.getText());
        if(menuteller.ambil(nominal)){
            JOptionPane.showMessageDialog(null,"Uang senilai "+nominal+" berhasil diambil");
        }
        else{
            JOptionPane.showMessageDialog(null,"Maaf saldo tidak mencukupi!! :(");
        }
        MenuTeller1.setVisible(true);
        PanelAmbilTeller.setVisible(false);
    }//GEN-LAST:event_jBAmbilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuTeller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuTeller1;
    private javax.swing.JPanel PanelAmbilTeller;
    private javax.swing.JPanel PanelCekSaldoTeller;
    private javax.swing.JPanel PanelLoginTeller;
    private javax.swing.JPanel PanelSimpanTeller;
    private javax.swing.JPanel PanelTransferTeller;
    private javax.swing.JPasswordField Passwordteller;
    private javax.swing.JTextField Usernameteller;
    private javax.swing.JButton jBAmbil;
    private javax.swing.JButton jBKembaliAmbil;
    private javax.swing.JButton jBKembaliCekSaldo2;
    private javax.swing.JButton jBKembaliLogin;
    private javax.swing.JButton jBKembaliSimpan;
    private javax.swing.JButton jBKembaliSimpan1;
    private javax.swing.JButton jBLoginTeller;
    private javax.swing.JButton jBLogoutTeller;
    private javax.swing.JButton jBMenuAmbilTeller;
    private javax.swing.JButton jBMenuCekSaldoTeller;
    private javax.swing.JButton jBMenuSimpanTeller;
    private javax.swing.JButton jBSimpan;
    private javax.swing.JButton jBTombolTransfer;
    private javax.swing.JButton jBTransferTeller;
    private javax.swing.JLabel jLNasabah;
    private javax.swing.JLabel jLSaldo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTeller;
    private javax.swing.JTextField jTAmbil;
    private javax.swing.JTextField jTNominalTransfer;
    private javax.swing.JTextField jTRekTujuan;
    private javax.swing.JTextField jTSimpan;
    // End of variables declaration//GEN-END:variables
}
