package new_bank;
import javax.swing.JOptionPane;
public class MenuATM extends javax.swing.JFrame {
    ATM atm = new ATM();
    MainMenu mainmenu = new MainMenu();
    public MenuATM() {
        initComponents();
        PanelLoginOffline.setVisible(true);
        MenuOffline.setVisible(false);
        PanelCekSaldo.setVisible(false);
        PanelTransfer.setVisible(false);
        PanelAmbil.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLoginOffline = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jBLoginOffline = new javax.swing.JButton();
        jBKembaliLogin = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        MenuOffline = new javax.swing.JPanel();
        jLNasabah = new javax.swing.JLabel();
        jBMenuCekSaldo = new javax.swing.JButton();
        jBMenuAmbil = new javax.swing.JButton();
        jBTransfer = new javax.swing.JButton();
        jBLogout = new javax.swing.JButton();
        jLabelAtm = new javax.swing.JLabel();
        PanelCekSaldo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLSaldo = new javax.swing.JLabel();
        jBKembaliCekSaldo = new javax.swing.JButton();
        PanelTransfer = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTRekTujuan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTNominalTransfer = new javax.swing.JTextField();
        jBTombolTransfer = new javax.swing.JButton();
        jBKembaliSimpan1 = new javax.swing.JButton();
        PanelAmbil = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTAmbil = new javax.swing.JTextField();
        jBKembaliAmbil = new javax.swing.JButton();
        jBAmbil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelLoginOffline.setBackground(new java.awt.Color(26, 15, 128));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(251, 241, 241));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN ATM");

        jLabel2.setForeground(new java.awt.Color(254, 247, 247));
        jLabel2.setText("Username");

        jLabel3.setForeground(new java.awt.Color(253, 251, 251));
        jLabel3.setText("Password");

        Username.setText("Username");
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });

        jBLoginOffline.setBackground(new java.awt.Color(244, 227, 29));
        jBLoginOffline.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBLoginOffline.setForeground(new java.awt.Color(24, 19, 52));
        jBLoginOffline.setText("Login");
        jBLoginOffline.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBLoginOffline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLoginOfflineActionPerformed(evt);
            }
        });

        jBKembaliLogin.setBackground(new java.awt.Color(206, 30, 5));
        jBKembaliLogin.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBKembaliLogin.setForeground(new java.awt.Color(254, 254, 254));
        jBKembaliLogin.setText("Kembali");
        jBKembaliLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBKembaliLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBKembaliLoginActionPerformed(evt);
            }
        });

        Password.setText("jPasswordField1");

        javax.swing.GroupLayout PanelLoginOfflineLayout = new javax.swing.GroupLayout(PanelLoginOffline);
        PanelLoginOffline.setLayout(PanelLoginOfflineLayout);
        PanelLoginOfflineLayout.setHorizontalGroup(
            PanelLoginOfflineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginOfflineLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(PanelLoginOfflineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelLoginOfflineLayout.createSequentialGroup()
                        .addGroup(PanelLoginOfflineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBKembaliLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                        .addGroup(PanelLoginOfflineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelLoginOfflineLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jBLoginOffline, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelLoginOfflineLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(Password))))
                    .addGroup(PanelLoginOfflineLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLoginOfflineLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        PanelLoginOfflineLayout.setVerticalGroup(
            PanelLoginOfflineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginOfflineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLoginOfflineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLoginOfflineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(PanelLoginOfflineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLoginOffline)
                    .addComponent(jBKembaliLogin))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        MenuOffline.setBackground(new java.awt.Color(26, 15, 128));

        jLNasabah.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLNasabah.setForeground(new java.awt.Color(251, 241, 241));
        jLNasabah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLNasabah.setText("WELCOME USER");

        jBMenuCekSaldo.setBackground(new java.awt.Color(244, 227, 29));
        jBMenuCekSaldo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBMenuCekSaldo.setForeground(new java.awt.Color(24, 19, 52));
        jBMenuCekSaldo.setText("Cek Saldo");
        jBMenuCekSaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBMenuCekSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMenuCekSaldoActionPerformed(evt);
            }
        });

        jBMenuAmbil.setBackground(new java.awt.Color(244, 227, 29));
        jBMenuAmbil.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBMenuAmbil.setForeground(new java.awt.Color(24, 19, 52));
        jBMenuAmbil.setText("Ambil");
        jBMenuAmbil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBMenuAmbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMenuAmbilActionPerformed(evt);
            }
        });

        jBTransfer.setBackground(new java.awt.Color(244, 227, 29));
        jBTransfer.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBTransfer.setText("Transfer");
        jBTransfer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTransferActionPerformed(evt);
            }
        });

        jBLogout.setBackground(new java.awt.Color(206, 30, 5));
        jBLogout.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBLogout.setForeground(new java.awt.Color(254, 254, 254));
        jBLogout.setText("Logout");
        jBLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLogoutActionPerformed(evt);
            }
        });

        jLabelAtm.setForeground(new java.awt.Color(254, 254, 254));
        jLabelAtm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAtm.setText("jLabel4");

        javax.swing.GroupLayout MenuOfflineLayout = new javax.swing.GroupLayout(MenuOffline);
        MenuOffline.setLayout(MenuOfflineLayout);
        MenuOfflineLayout.setHorizontalGroup(
            MenuOfflineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuOfflineLayout.createSequentialGroup()
                .addGroup(MenuOfflineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuOfflineLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLNasabah, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuOfflineLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(MenuOfflineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBMenuCekSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBMenuAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(MenuOfflineLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelAtm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MenuOfflineLayout.setVerticalGroup(
            MenuOfflineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuOfflineLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLNasabah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAtm)
                .addGap(18, 18, 18)
                .addComponent(jBMenuCekSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBMenuAmbil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBTransfer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelCekSaldo.setBackground(new java.awt.Color(26, 15, 128));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 254, 254));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CEK SALDO");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(254, 254, 254));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Saldo Anda  :");

        jLSaldo.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLSaldo.setForeground(new java.awt.Color(254, 254, 254));
        jLSaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLSaldo.setText("100000");

        jBKembaliCekSaldo.setBackground(new java.awt.Color(206, 30, 5));
        jBKembaliCekSaldo.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jBKembaliCekSaldo.setForeground(new java.awt.Color(254, 254, 254));
        jBKembaliCekSaldo.setText("Kembali");
        jBKembaliCekSaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBKembaliCekSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBKembaliCekSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCekSaldoLayout = new javax.swing.GroupLayout(PanelCekSaldo);
        PanelCekSaldo.setLayout(PanelCekSaldoLayout);
        PanelCekSaldoLayout.setHorizontalGroup(
            PanelCekSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCekSaldoLayout.createSequentialGroup()
                .addGroup(PanelCekSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCekSaldoLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCekSaldoLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCekSaldoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelCekSaldoLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jBKembaliCekSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelCekSaldoLayout.setVerticalGroup(
            PanelCekSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCekSaldoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBKembaliCekSaldo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelTransfer.setBackground(new java.awt.Color(26, 15, 128));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("TRANSFER");

        jTRekTujuan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTRekTujuan.setText("1001");
        jTRekTujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTRekTujuanActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(254, 254, 254));
        jLabel10.setText("Rekening Tujuan  :");

        jLabel11.setForeground(new java.awt.Color(254, 254, 254));
        jLabel11.setText("Nominal  :");

        jTNominalTransfer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTNominalTransfer.setText("50000");
        jTNominalTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNominalTransferActionPerformed(evt);
            }
        });

        jBTombolTransfer.setBackground(new java.awt.Color(244, 227, 29));
        jBTombolTransfer.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBTombolTransfer.setText("Transfer");
        jBTombolTransfer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBTombolTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTombolTransferActionPerformed(evt);
            }
        });

        jBKembaliSimpan1.setBackground(new java.awt.Color(206, 30, 5));
        jBKembaliSimpan1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBKembaliSimpan1.setForeground(new java.awt.Color(254, 254, 254));
        jBKembaliSimpan1.setText("Kembali");
        jBKembaliSimpan1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBKembaliSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBKembaliSimpan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTransferLayout = new javax.swing.GroupLayout(PanelTransfer);
        PanelTransfer.setLayout(PanelTransferLayout);
        PanelTransferLayout.setHorizontalGroup(
            PanelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTransferLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTNominalTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTRekTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116))
            .addGroup(PanelTransferLayout.createSequentialGroup()
                .addGroup(PanelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTransferLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(PanelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)))
                    .addGroup(PanelTransferLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelTransferLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jBKembaliSimpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBTombolTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        PanelTransferLayout.setVerticalGroup(
            PanelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTransferLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTRekTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTNominalTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTombolTransfer)
                    .addComponent(jBKembaliSimpan1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelAmbil.setBackground(new java.awt.Color(26, 15, 128));

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(254, 254, 254));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("AMBIL");

        jTAmbil.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTAmbil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTAmbil.setText("100000");

        jBKembaliAmbil.setBackground(new java.awt.Color(206, 30, 5));
        jBKembaliAmbil.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBKembaliAmbil.setForeground(new java.awt.Color(254, 254, 254));
        jBKembaliAmbil.setText("Kembali");
        jBKembaliAmbil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBKembaliAmbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBKembaliAmbilActionPerformed(evt);
            }
        });

        jBAmbil.setBackground(new java.awt.Color(244, 227, 29));
        jBAmbil.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBAmbil.setText("Ambil");
        jBAmbil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAmbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAmbilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAmbilLayout = new javax.swing.GroupLayout(PanelAmbil);
        PanelAmbil.setLayout(PanelAmbilLayout);
        PanelAmbilLayout.setHorizontalGroup(
            PanelAmbilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAmbilLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(PanelAmbilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAmbilLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jTAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelAmbilLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jBKembaliAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        PanelAmbilLayout.setVerticalGroup(
            PanelAmbilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAmbilLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelAmbilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAmbil)
                    .addComponent(jBKembaliAmbil))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelAmbil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelCekSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MenuOffline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelLoginOffline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelLoginOffline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MenuOffline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelCekSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelAmbil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTRekTujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTRekTujuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTRekTujuanActionPerformed

    private void jTNominalTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNominalTransferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNominalTransferActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void jBLoginOfflineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLoginOfflineActionPerformed
        // TODO add your handling code here:
        String user = Username.getText();
        int pass = Integer.parseInt(Password.getText());
        
        if(atm.login(user,pass)){
            PanelLoginOffline.setVisible(false);
            MenuOffline.setVisible(true);
            PanelCekSaldo.setVisible(false);
            PanelTransfer.setVisible(false);
            PanelAmbil.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null,"Account tidak ditemukan!!!");
        }
        jLNasabah.setText("WELCOME " + user);
        jLabelAtm.setText("Alamat ATM : " + atm.alamat);
    }//GEN-LAST:event_jBLoginOfflineActionPerformed

    private void jBMenuCekSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMenuCekSaldoActionPerformed
        // TODO add your handling code here:
        MenuOffline.setVisible(false);
        PanelCekSaldo.setVisible(true);
        jLSaldo.setText(atm.cekSaldo());
    }//GEN-LAST:event_jBMenuCekSaldoActionPerformed

    private void jBKembaliCekSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBKembaliCekSaldoActionPerformed
        // TODO add your handling code here:
        MenuOffline.setVisible(true);
        PanelCekSaldo.setVisible(false);
    }//GEN-LAST:event_jBKembaliCekSaldoActionPerformed

    private void jBMenuAmbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMenuAmbilActionPerformed
        // TODO add your handling code here:
        MenuOffline.setVisible(false);
        PanelAmbil.setVisible(true);
        
        
    }//GEN-LAST:event_jBMenuAmbilActionPerformed

    private void jBAmbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAmbilActionPerformed
        // TODO add your handling code here:
        long nominal = Long.parseLong(jTAmbil.getText());
        if(atm.ambil(nominal)){
            JOptionPane.showMessageDialog(null,"Uang senilai "+nominal+" berhasil diambil");            
        }
        else{
            JOptionPane.showMessageDialog(null,"Maaf saldo tidak mencukupi!! :(");
        }
        MenuOffline.setVisible(true);
        PanelAmbil.setVisible(false);
    }//GEN-LAST:event_jBAmbilActionPerformed

    private void jBKembaliAmbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBKembaliAmbilActionPerformed
        // TODO add your handling code here:
        MenuOffline.setVisible(true);
        PanelAmbil.setVisible(false);
    }//GEN-LAST:event_jBKembaliAmbilActionPerformed

    private void jBLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLogoutActionPerformed
        // TODO add your handling code here:
        MenuOffline.setVisible(false);
        PanelLoginOffline.setVisible(true);
    }//GEN-LAST:event_jBLogoutActionPerformed

    private void jBTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTransferActionPerformed
        // TODO add your handling code here:
        MenuOffline.setVisible(false);
        PanelTransfer.setVisible(true);
        
        
    }//GEN-LAST:event_jBTransferActionPerformed

    private void jBTombolTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTombolTransferActionPerformed
        // TODO add your handling code here:
        long rekening = Long.parseLong(jTRekTujuan.getText());
        long nominal = Long.parseLong(jTNominalTransfer.getText());
        
        if(atm.transfer(nominal, rekening)){
            JOptionPane.showMessageDialog(null,"Berhasil Ditransfer!!");            
        }
        else{
            JOptionPane.showMessageDialog(null,"Rekening tidak Ditemukan/Saldo tidak cukup!!");
        }
        MenuOffline.setVisible(true);
        PanelTransfer.setVisible(false);
    }//GEN-LAST:event_jBTombolTransferActionPerformed

    private void jBKembaliLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBKembaliLoginActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        mainmenu.setVisible(true);
    }//GEN-LAST:event_jBKembaliLoginActionPerformed

    private void jBKembaliSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBKembaliSimpan1ActionPerformed
        // TODO add your handling code here:
        MenuOffline.setVisible(true);
        PanelTransfer.setVisible(false);
    }//GEN-LAST:event_jBKembaliSimpan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuATM().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuOffline;
    private javax.swing.JPanel PanelAmbil;
    private javax.swing.JPanel PanelCekSaldo;
    private javax.swing.JPanel PanelLoginOffline;
    private javax.swing.JPanel PanelTransfer;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Username;
    private javax.swing.JButton jBAmbil;
    private javax.swing.JButton jBKembaliAmbil;
    private javax.swing.JButton jBKembaliCekSaldo;
    private javax.swing.JButton jBKembaliLogin;
    private javax.swing.JButton jBKembaliSimpan1;
    private javax.swing.JButton jBLoginOffline;
    private javax.swing.JButton jBLogout;
    private javax.swing.JButton jBMenuAmbil;
    private javax.swing.JButton jBMenuCekSaldo;
    private javax.swing.JButton jBTombolTransfer;
    private javax.swing.JButton jBTransfer;
    private javax.swing.JLabel jLNasabah;
    private javax.swing.JLabel jLSaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAtm;
    private javax.swing.JTextField jTAmbil;
    private javax.swing.JTextField jTNominalTransfer;
    private javax.swing.JTextField jTRekTujuan;
    // End of variables declaration//GEN-END:variables
}
